### ISSUE TITLE
Add email template to GitHub

### ISSUE THREAD

**Issue by mattl** [creativecommons/donate-2015#2]

**Comment by ewilfong** [comment]
Where would be the best place to put this in GitHUb?  In this repository or somewhere else?

**Comment by mattl** [comment]
Yeah, here is fine. Hopefully you have write access to this repo. Checking that now.

**Comment by mattl** [comment]
You didn't, you do now. @robmyers -- let's keep @creativecommons/trilogy isolated to this repo for now.

**Comment by ewilfong** [comment]
Thanks. Added.
