### ISSUE TITLE
Emails are too wide in Safari

### ISSUE THREAD

**Issue by mattl** [creativecommons/donate-2015#7]
![safari](https://cloud.githubusercontent.com/assets/33296/7704465/838b84da-fe0c-11e4-92b7-60978e8358a2.png)

I suspect the image is throwing things off, but maybe you have some better insights?

**Comment by ewilfong** [comment]
Yes, correct.  The image was inserted without any responsive CSS classes/styles associated with it and thus it broke the responsive nature of the template. When inserting an image into this template, please refer to the email template documentation.  Here's a bookmark of the relevant code for inserting a full-width image:

https://docs.google.com/document/d/1xvaJG5m1nPpVnj0Ef9gVGG5IoV_0FMxlPKKtuBJxqiI/edit#bookmark=id.cqjjnjvpogyd

If the next email has an image, let me know when the email is coded in CiviCRM and I can review.

**Comment by mattl** [comment]
It did have a class that got added last week as Ryan wanted big images, not just the 200x200px images. Can we use 'callout' for wide images that get scaled down appropriately on mobile, etc?

**Comment by ewilfong** [comment]
Absolutely. The code linked above is for full-width images.  I'll put together a version of the email referenced here that scales appropriately as an example.

**Comment by mattl** [comment]
Could you update the remaining draft emails in Civi and send me a test?
Also a test to diane@ would be great.

---

Matt Lee
Creative Commons
Boston, MA, USA

**Comment by ewilfong** [comment]
Sent you and Diane a test of https://donate.creativecommons.org/civicrm/mailing/send?_qf_Upload_display=true&qfKey=bbd285553e35df296500c8d194ddf320_4869

Are the remaining drafts called "CC/Trilogy Real Email #4" and "CC/Trilogy Real Email #5"?

**Comment by mattl** [comment]
Yep, those are the emails :)

---

Matt Lee
Creative Commons
Boston, MA, USA

**Comment by ewilfong** [comment]
I've updated both of those emails with the responsive CSS and linked both to the campaign donation page. I tested both email in Litmus to ensure they are laid out correctly in all email clients.
