### ISSUE TITLE
Unsubscribe link not linked in some clients

### ISSUE THREAD

**Issue by mattl** [creativecommons/donate-2015#8]
Let's make sure we're linking to the opt-out URL, not just expecting the client will do that.

![screenshot_2015-05-19-03-57-33](https://cloud.githubusercontent.com/assets/33296/7704490/bccbfdb0-fe0c-11e4-80c6-2c4e411428bb.png)

**Comment by ewilfong** [comment]
No problem, I updated the email template in GitHub and the default footer in CiviCRM.

https://github.com/creativecommons/donate-2015/commit/5b3a164074a25d7d2132e999feaeea96d9bccd3f
